// Trades / Gewerke
export const trades = [
  {
    slug: 'dachdecker',
    name: 'Dachdecker',
    description: 'Dachdecker, Dachdeckung, Dachreparatur',
    services: [
      'Dachreparatur und Notdienst',
      'Dachneueindeckung',
      'Dachsanierung und Dämmung',
      'Dachfenster-Einbau',
      'Dachrinnen und Fallrohre',
      'Dachinspektion und Wartung',
    ],
    keywords: ['Dach', 'Schiefer', 'Ziegel', 'Dachstuhl', 'Dachboden', 'Regenrinne'],
    buildingTypes: 'Altbauten mit Schiefer- und Ziegeldächern, Neubauten mit Flachdächern',
    painPoints: 'undichte Stellen, Sturmschäden, Alterserscheinungen, fehlende Dämmung',
  },
  {
    slug: 'elektriker',
    name: 'Elektriker',
    description: 'Elektroinstallation, Elektriker, Elektrobetrieb',
    services: [
      'Elektroinstallationen',
      'Stromausfall-Reparatur',
      'Sicherungskasten-Modernisierung',
      'Smart-Home-Installation',
      'Elektroprüfung nach VDE',
      'Beleuchtungsplanung',
    ],
    keywords: ['Strom', 'Elektro', 'Sicherung', 'Leitung', 'Schaltschrank', 'Steckdose'],
    buildingTypes: 'Altbauten mit veralteter Elektrik, Neubauten mit moderner Smart-Home-Verkabelung',
    painPoints: 'häufige Sicherungsauslösungen, veraltete Elektroinstallationen, zu wenig Steckdosen',
  },
  {
    slug: 'klempner',
    name: 'Klempner',
    description: 'Klempner, Sanitär, Heizung, Rohrreinigung',
    services: [
      'Rohrreinigung und -sanierung',
      'Heizungsinstallation und -reparatur',
      'Badmodernisierung',
      'Wasserschaden-Behebung',
      'Toiletten- und Waschbecken-Installation',
      '24h Notdienst',
    ],
    keywords: ['Wasser', 'Rohr', 'Heizung', 'Abfluss', 'Armatur', 'Sanitär'],
    buildingTypes: 'Altbauten mit veralteten Bleirohren, Neubauten mit moderner Fußbodenheizung',
    painPoints: 'verstopfte Abflüsse, undichte Rohre, kalte Heizkörper, Wasserschäden',
  },
  {
    slug: 'schornsteinfeger',
    name: 'Schornsteinfeger',
    description: 'Schornsteinfeger, Kaminkehrer, Feuerstätten-Prüfung',
    services: [
      'Regelmäßige Kehrung und Überprüfung',
      'Feuerstätten-Bescheid',
      'Schornstein-Sanierung',
      'Kamin- und Ofenreinigung',
      'Abgasuntersuchung',
      'Beratung zu modernen Heizsystemen',
    ],
    keywords: ['Kamin', 'Schornstein', 'Ofen', 'Abgas', 'Kehrung', 'Feuerstätte'],
    buildingTypes: 'Altbauten mit historischen Kaminen, Neubauten mit modernen Pelletöfen',
    painPoints: 'Rauchprobleme, verstopfte Schornsteine, fehlende Kehrung, unsichere Abgaswege',
  },
  {
    slug: 'maler',
    name: 'Maler',
    description: 'Maler, Lackierer, Fassadenanstrich',
    services: [
      'Innenraum-Streicharbeiten',
      'Fassadenanstrich und -sanierung',
      'Tapezierarbeiten',
      'Lackierarbeiten',
      'Bodengestaltung',
      'Farberatung und Moodboards',
    ],
    keywords: ['Farbe', 'Lack', 'Tapete', 'Fassade', 'Anstrich', 'Renovierung'],
    buildingTypes: 'Altbauten mit Stuckdecken und historischen Farbschichten, Neubauten mit Raufasertapeten',
    painPoints: 'abblätternde Farbe, Schimmel, veraltete Tapeten, stumpfe Farben',
  },
  {
    slug: 'fliesenleger',
    name: 'Fliesenleger',
    description: 'Fliesenleger, Fliesenverlegung, Badsanierung',
    services: [
      'Badfliesen-Verlegung',
      'Küchenrückwand-Gestaltung',
      'Bodenfliesen in allen Räumen',
      'Wärmedämm-Verbundsysteme',
      'Natursteinverlegung',
      'Altfliesen-Entfernung',
    ],
    keywords: ['Fliese', 'Boden', 'Bad', 'Küche', 'Naturstein', 'Verlegung'],
    buildingTypes: 'Altbauten mit kleinen Bädern, Neubauten mit bodengleichen Duschen',
    painPoints: 'beschädigte Fugen, abgeplatzte Fliesen, veraltete Badgestaltung, Wasserschäden',
  },
  {
    slug: 'schreiner',
    name: 'Schreiner',
    description: 'Schreiner, Tischler, Möbelbau, Innenausbau',
    services: [
      'Maßgefertigte Möbel',
      'Küchenbau',
      'Innenausbau und Trockenbau',
      'Treppenbau',
      'Fenster- und Türen-Einbau',
      'Restaurierung von Holzmöbeln',
    ],
    keywords: ['Holz', 'Möbel', 'Küche', 'Tür', 'Fenster', 'Treppen'],
    buildingTypes: 'Altbauten mit historischen Holztüren und Dielenböden, Neubauten mit modernen Einbauküchen',
    painPoints: 'quietschige Türen, abgenutzte Holzböden, zu wenig Stauraum, veraltete Küchen',
  },
  {
    slug: 'gartenpflege',
    name: 'Gartenpflege',
    description: 'Gartenpflege, Gartengestaltung, Baumpflege',
    services: [
      'Rasenpflege und Vertikutierung',
      'Hecke schneiden und Gestaltung',
      'Baumfällung und Baumpflege',
      'Gartengestaltung und Planung',
      'Unkrautbekämpfung',
      'Gartenwintervorbereitung',
    ],
    keywords: ['Garten', 'Rasen', 'Hecke', 'Baum', 'Pflanze', 'Boden'],
    buildingTypes: 'Reihenhäuser mit kleinen Gärten, Einfamilienhäuser mit großen Grundstücken',
    painPoints: 'unkontrolliertes Unkrautwachstum, kahle Stellen im Rasen, überwucherte Hecken, kranke Bäume',
  },
]

// Cities / Städte
export const cities = [
  {
    slug: 'berlin',
    name: 'Berlin',
    state: 'Berlin',
    population: '3,7 Millionen',
    district: 'Prenzlauer Berg',
    landmark: 'Brandenburger Tor',
    weatherPattern: 'starke Regenfälle im Herbst und Winter, wechselhafte Temperaturen',
    buildingTypes: 'Altbauten mit Schieferdächern, Plattenbau-Neubauten, Loft-Wohnungen',
    industryNotes: 'Hohe Dichte an Gewerbebetrieben, viele denkmalgeschützte Gebäude, aktiver Baumarkt',
  },
  {
    slug: 'muenchen',
    name: 'München',
    state: 'Bayern',
    population: '1,5 Millionen',
    district: 'Schwabing',
    landmark: 'Frauenkirche',
    weatherPattern: 'kalte Winter mit Schneefall, warme Sommer, häufiger Regen im Frühjahr',
    buildingTypes: 'Historische Altbauten in Bogenhausen, moderne Wohnkomplexe, traditionelle bayrische Architektur',
    industryNotes: 'Hohe Kaufkraft, strenge Bauvorschriften, viele Premium-Anbieter, wachsende Stadt',
  },
  {
    slug: 'hamburg',
    name: 'Hamburg',
    state: 'Hamburg',
    population: '1,9 Millionen',
    district: 'Eppendorf',
    landmark: 'Elbphilharmonie',
    weatherPattern: 'feuchtes maritimes Klima, häufige Stürme im Herbst, milde Winter',
    buildingTypes: 'Kontorhäuser, Gründerzeit-Altbauten, moderne Hafencity-Architektur',
    industryNotes: 'Hohe Nachfrage nach Handwerksleistungen, viele Eigentümergemeinschaften, hohe Mietpreise',
  },
  {
    slug: 'koeln',
    name: 'Köln',
    state: 'Nordrhein-Westfalen',
    population: '1,1 Millionen',
    district: 'Ehrenfeld',
    landmark: 'Kölner Dom',
    weatherPattern: 'milde Winter, regenreiche Jahreszeiten, häufige Gewitter im Sommer',
    buildingTypes: 'Wohnhäuser aus der Gründerzeit, moderne Wohnblocks, historische Altstadthäuser',
    industryNotes: 'Große Stadt mit vielen Stadtbezirken, hohe Nachfrage nach Renovierung, viele Mieter',
  },
  {
    slug: 'frankfurt',
    name: 'Frankfurt am Main',
    state: 'Hessen',
    population: '760.000',
    district: 'Sachsenhausen',
    landmark: 'Römer',
    weatherPattern: 'warme Sommer, milde Winter, Regen verteilt über das Jahr',
    buildingTypes: 'Hochhäuser im Bankenviertel, historische Fachwerkhäuser, moderne Wohnanlagen',
    industryNotes: 'Hohe Umzugsrate, viele Expats, internationale Nachfrage, teures Wohnen',
  },
  {
    slug: 'stuttgart',
    name: 'Stuttgart',
    state: 'Baden-Württemberg',
    population: '630.000',
    district: 'West',
    landmark: 'Fernsehturm',
    weatherPattern: 'sonniges Klima, Föhn-Winde, gelegentliche Hagelstürme',
    buildingTypes: 'Einfamilienhäuser mit Gärten, Kessellage-Spezialitäten, moderne Bauweise',
    industryNotes: 'Porsche-/Daimler-Geld, hohe Kaufkraft, viele Eigenheimbesitzer, technikaffin',
  },
  {
    slug: 'duesseldorf',
    name: 'Düsseldorf',
    state: 'Nordrhein-Westfalen',
    population: '620.000',
    district: 'Oberkassel',
    landmark: 'Rheinturm',
    weatherPattern: 'milde Temperaturen, regenreich, selten Extremwetter',
    buildingTypes: 'Noble Altbauten in der Innenstadt, moderne Wohnquartiere, Künstlerateliers',
    industryNotes: 'Modestadt, hohe Lebensqualität, viele DINKs, Premium-Segment stark',
  },
  {
    slug: 'dortmund',
    name: 'Dortmund',
    state: 'Nordrhein-Westfalen',
    population: '590.000',
    district: 'Kreuzviertel',
    landmark: 'Signal Iduna Park',
    weatherPattern: 'gemäßigtes Klima, regelmäßiger Niederschlag, selten Dürre',
    buildingTypes: 'Arbeiterwohnquartiere, Gründerzeit-Häuser, Plattenbauten, Neubausiedlungen',
    industryNotes: 'Strukturwandel-Stadt, viele Sanierungsprojekte, wachsender Handwerksbedarf',
  },
  {
    slug: 'essen',
    name: 'Essen',
    state: 'Nordrhein-Westfalen',
    population: '580.000',
    district: 'Rüttenscheid',
    landmark: 'Zeche Zollverein',
    weatherPattern: 'ähnlich Dortmund, industriegeprägtes Mikroklima',
    buildingTypes: 'Kolonie-Häuser, Villen im Süden, urbane Neubauten',
    industryNotes: 'Kulturhauptstadt-Erbe, viele Sanierungsbedürftige Gebäude, wachsende Innenstadt',
  },
  {
    slug: 'leipzig',
    name: 'Leipzig',
    state: 'Sachsen',
    population: '600.000',
    district: 'Südvorstadt',
    landmark: 'Monument to the Battle of the Nations',
    weatherPattern: 'kontinentales Klima, warme Sommer, kalte Winter, trockener als NRW',
    buildingTypes: 'Altbau-Wohnblocks, Wohnungsbauserien, sanierte Gründerzeithäuser',
    industryNotes: 'Boom-Stadt, massiver Zuzug, hoher Sanierungsbedarf, aufstrebendes Gewerbe',
  },
]
