// ═══════════════════════════════════════════════════════════════
// CITY FACTS — Lokale Fakten pro Stadt (für einzigartige Seiten)
// ═══════════════════════════════════════════════════════════════
// Quelle: Allgemein bekannte, örtliche Gegebenheiten (Bausubstanz,
// Stadtviertel, Lage). KEINE erfundenen Statistiken oder Firmen.
// Wird von generate-city-pages-v2.js genutzt.
// ═══════════════════════════════════════════════════════════════

const CITY_FACTS = {
  'bergkamen': {
    name: 'Bergkamen',
    character: 'ruhige Mittelstadt am Datteln-Hamm-Kanal, geprägt von Bergbau-Tradition und grünen Wohngebieten',
    housing: 'viele Siedlungshäuser aus den 1920er- bis 1950er-Jahren sowie gepflegte Eigenheime und Bungalows der Nachkriegszeit',
    districts: ['Oberaden', 'Weddinghofen', 'Rünthe'],
    tradeNote: 'Die älteren Siedlungshäuser in den Ortsteilen haben je nach Baujahr sehr unterschiedliche Dach-, Elektro- und Sanitärinstallationen — eine Fachbegutachtung vor jeder Maßnahme lohnt sich hier besonders.',
    surroundings: 'flaches Gelände am Kanal, kurze Wege nach Kamen, Unna und Dortmund',
  },
  'bochum': {
    name: 'Bochum',
    character: 'vielfältige Großstadt im Herzen des Ruhrgebiets, vom Gründerzeit-Quartier bis zum Uni-Campus',
    housing: 'Mischung aus Altbau in Ehrenfeld und Wiemelhausen, Bergmanns-Doppelhäuser aus den 1920ern und Nachkriegs-Neubaugebieten wie Querenburg',
    districts: ['Wiemelhausen', 'Ehrenfeld', 'Querenburg', 'Hustadt'],
    tradeNote: 'Zwischen den Jahrhundertwende-Häusern an der Bochumer Südstadt und den Siedlungen des Bergbaus liegen oft 60 Jahre Bautechnik — wir kennen beide Seiten der Stadt und planen entsprechend.',
    surroundings: 'direkt an der A40 und A43, eingebettet zwischen Dortmund, Essen und Witten',
  },
  'castrop-rauxel': {
    name: 'Castrop-Rauxel',
    character: 'grüne Stadt am Rande des Ruhrgebiets mit Zechen-Tradition und dörflichen Ortsteilen',
    housing: 'viele Siedlungshäuser der Zeche Erin sowie Eigenheimsiedlungen aus den 1950er- bis 1970er-Jahren, dazu Fachwerk in den alten Ortsteilen',
    districts: ['Rauxel', 'Ickern', 'Henrichenburg'],
    tradeNote: 'Die Häuser der Zechensiedlungen stehen oft unter Denkmalschutz oder in Ensembles — hier zählt Erfahrung mit behördlichen Vorgaben und originalgetreuen Materialien.',
    surroundings: 'zwischen Dortmund, Recklinghausen und Herne, direkt an der A2 und A42',
  },
  'dortmund': {
    name: 'Dortmund',
    character: 'metropole des Ostens: von der Nordstadt über das Uni-Viertel bis zum Phoenix-See',
    housing: 'kontrastreiche Bausubstanz — Altbau in der Nordstadt und in Körne, Einfamilienhaus-Siedlungen in Aplerbeck, Hombruch und Hörde, neue Quartiere am Phoenix-See',
    districts: ['Nordstadt', 'Körne', 'Aplerbeck', 'Hörde', 'Hombruch'],
    tradeNote: 'Vom sanierungsbedürftigen Altbau bis zum Neubau am See: Dortmund verlangt Handwerkern eine Bandbreite ab, die wir im Alltag haben — inklusive Erfahrung mit Förderprogrammen der Stadtwerke und der Stadt Dortmund.',
    surroundings: 'Kreuzung von A1, A2 und A45, grüner Westfalenpark, Ardeygebirge im Osten',
  },
  'ennepetal': {
    name: 'Ennepetal',
    character: 'Stadt in grüner Talkessellage an der Ennepe, eingebettet zwischen Hagen und dem Sauerland',
    housing: 'erheblich ältere Bausubstanz im Tal (Gründerzeit und Siedlungshäuser in Altenvoerde und Milspe), dazu Eigenheime an den Hängen',
    districts: ['Altenvoede', 'Milspe', 'Kabel'],
    tradeNote: 'Hanglagen und enge Tälern bedeuten: Zufahrten, Gerüste und Materialtransport wollen gut geplant sein — wir kalkulieren das von Anfang an mit ein.',
    surroundings: 'an der B54 zwischen Hagen und Gevelsberg, direkt am Sauerlandrand',
  },
  'froendenberg': {
    name: 'Fröndenberg',
    character: 'kleine, ländlich geprägte Stadt an der Ruhr mit Ardey-Berg im Rücken',
    housing: 'Eigenheime, alte Bauernhöfe und Fachwerk in den Ortsteilen, dazu gepflegte Siedlungen aus den 1960er-Jahren',
    districts: ['Frömern', 'Langschede', 'Ardey'],
    tradeNote: 'Alte Hofstellen und Fachwerk verlangen traditionelle Handwerkstechniken — gleichzeitig wollen viele Eigentümer hier modernisieren, ohne den Charakter zu verlieren.',
    surroundings: 'zwischen Unna, Menden und dem Sauerland, Ruhr und Ardey prägen das Bild',
  },
  'gevelsberg': {
    name: 'Gevelsberg',
    character: 'Stadt über dem Ennepe-Tal, bekannt für Villen und eine enge, bergige Stadtstruktur',
    housing: 'Gründerzeit-Villen und Jugendstilhäuser in Silschede und im Zentrum, dazu Siedlungshäuser an den Hanglagen',
    districts: ['Silschede', 'Berge', 'Asbeck'],
    tradeNote: 'Hanggrundstücke, enge Zufahrten und wertvolle Altbauten: Hier ist präzise Planung gefragt — vom Gerüst bis zur Materialauswahl für anspruchsvolle Fassaden.',
    surroundings: 'im Ennepe-Ruhr-Kreis zwischen Ennepetal, Schwelm und Wuppertal',
  },
  'hagen': {
    name: 'Hagen',
    character: 'die vier-Täler-Stadt: Ennepe, Volme, Lenne und Ruhrtal prägen Stadtform und Baustil',
    housing: 'sehr viele Hanglagen mit Gründerzeit-Häusern in Wehringhausen und Haspe, dem Villenviertel am Goldberg und Eigenheimen in Hohenlimburg',
    districts: ['Wehringhausen', 'Haspe', 'Hohenlimburg', 'Eilpe'],
    tradeNote: 'Hagen ist die Stadt der Hanglagen: Drainage, Gründung und Zufahrten spielen hier eine besondere Rolle — wir wissen, was Häuser an Hagens Hängen brauchen.',
    surroundings: 'Schnittpunkt von A1, A45 und A46, Tor zum Sauerland',
  },
  'hattingen': {
    name: 'Hattingen',
    character: 'eine der ältesten Städte Westfalens, mit historischer Altstadt direkt an der Ruhr',
    housing: 'Fachwerk und Altbau in der mittelalterlichen Altstadt, Hofstellen in Blankenstein und Niederwenigern, dazu ruhige Eigenheimgebiete am Stadtrand',
    districts: ['Altstadt', 'Blankenstein', 'Niederwenigern', 'Welper'],
    tradeNote: 'Denkmalgeschützte Altbausubstanz verlangt behördliche Genehmigungen und passende Materialien — von Schiefer bis Kalkputz — und Erfahrung mit dem Denkmalamt.',
    surroundings: 'an der Ruhr zwischen Bochum und Witten, im Ardeyvorland',
  },
  'herne': {
    name: 'Herne',
    character: 'Zechenstadt mit Herz: von Wanne-Eickel bis zur Cranger Kirmes',
    housing: 'überdurchschnittlich viele Bergmanns-Siedlungen aus den 1920ern, Doppelhaushälften in langen Reihen, dazu Eigenheime in ruhigeren Lagen',
    districts: ['Wanne-Eickel', 'Crange', 'Sodingen', 'Röhlinghausen'],
    tradeNote: 'Die Zechensiedlungen Herness sind oft bauzeittypisch ausgeführt — gleiche Häuser, gleiche Bautechnik. Wir wissen, wo typische Schwachstellen dieser Baujahre liegen.',
    surroundings: 'zwischen Bochum, Recklinghausen und Dortmund, an A42 und A43',
  },
  'holzwickede': {
    name: 'Holzwickede',
    character: 'grüne, gefragte Wohnstadt am Dortmunder Flughafen mit Landhaus-Charakter',
    housing: 'viele gepflegte Einfamilienhaus-Siedlungen, Landhäuser und Villen, überwiegend aus den 1950er- bis 1980er-Jahren',
    districts: ['Hengstey', 'Dudenroth', 'Hixterwald'],
    tradeNote: 'Gepflegte Eigenheim-Quartiere mit durchgehenden Gärten: Hier zählen saubere Ausführung, Termintreue und ein gepflegter Umgang mit Grundstück und Hecke.',
    surroundings: 'zwischen Dortmund und Unna, direkt am Flughafen Dortmund',
  },
  'iserlohn': {
    name: 'Iserlohn',
    character: 'Großstadt am Sauerlandrand: Hügel, Gärten und eine starke Heimatverbundenheit',
    housing: 'viele Eigenheime und Villen (etwa am Obergrüne), solider Altbau in der Altstadt und in Letmathe, große Gärten sind hier Standard',
    districts: ['Altstadt', 'Letmathe', 'Obergrüne', 'Baarburg'],
    tradeNote: 'Grundstücke mit Gärten und Bäumen brauchen pflegliche Arbeitstechniken — von der Terrasse unter Kastanien bis zur Dachrinne über der Einfahrt unter Altbäumen.',
    surroundings: 'im Märkischen Kreis, zwischen Hagen, Hemer und Menden',
  },
  'kamen': {
    name: 'Kamen',
    character: 'familienfreundliche Stadt zwischen Dortmund und Unna mit Zechen-Wurzeln',
    housing: 'Zechensiedlungen der Zechen Monopol und Haus Hermann, dazu grünere Neubaugebiete in Heeren-Werve und viele Reihen- und Doppelhäuser der 50er/60er',
    districts: ['Heeren-Werve', 'Methler', 'Süd'],
    tradeNote: 'Viele Häuser der 1950er- und 1960er-Jahre sind heute fällig für erste große Sanierungen — Dach, Bad und Elektro gleichzeitig im Blick zu behalten spart doppelte Kosten.',
    surroundings: 'an der A1 und A2, zwischen Dortmund, Unna und Bergkamen',
  },
  'luenen': {
    name: 'Lünen',
    character: 'Stadt an Lippe und Kanal: von Brambauers Zechensiedlungen bis zur ländlichen Nordstadt',
    housing: 'Siedlungshäuser rund um die ehemalige Zeche Minister Achenbach, Eigenheimsiedlungen in Nordlünen und solider Wohnungsbau entlang der Lippe',
    districts: ['Brambauer', 'Nordlünen', 'Lünern', 'Altlünen'],
    tradeNote: 'Von den langen Siedlungsstraßen Brambauers bis zu den Höfen im Norden: Bodenbeschaffenheit und Zufahrt unterscheiden sich je nach Ortsteil erheblich.',
    surroundings: 'im Kreis Unna, an der A1 und A43, Lippe und Datteln-Hamm-Kanal',
  },
  'schwelm': {
    name: 'Schwelm',
    character: 'bürgerliche Kleinstadt im Ennepe-Ruhr-Kreis mit Gründerzeit-Charme',
    housing: 'unverhältnismäßig viele Gründerzeit- und Jugendstilhäuser, gepflegte Altbau-Villen und solide Siedlungshäuser',
    districts: ['Altstadt', 'Hammerbruch', 'Loh'],
    tradeNote: 'Schwelms Altbau aus der Gründerzeit verlangt Sanierungs-Know-how: Fassaden, Stuck und alte Versorgungsleitungen brauchen Erfahrung und eine saubere Bestandsaufnahme.',
    surroundings: 'zwischen Ennepetal, Gevelsberg und Wuppertal, am Rand des Bergischen Landes',
  },
  'schwerte': {
    name: 'Schwerte',
    character: 'alte Hansestadt an der Ruhr mit Fachwerk-Altstadt und Zechen-Geschichte',
    housing: 'Fachwerk in der historischen Altstadt, Bergmannssiedlungen der Zechen Westhausen und Germania, Eigenheime in Ergste und Holzen',
    districts: ['Altstadt', 'Ergste', 'Holzen', 'Westhofen'],
    tradeNote: 'Fachwerk und Zechensiedlung auf engem Raum: Schwerte verlangt flexible Lösungen — vom vorsichtigen Umgang mit historischem Gefach bis zur Komplettsanierung der Siedlungshäuser.',
    surroundings: 'an der Ruhr zwischen Dortmund, Hagen und Iserlohn, direkt an der A1',
  },
  'sprockhoevel': {
    name: 'Sprockhövel',
    character: 'höher gelegene Wohngemeinde über dem Ruhrtal mit dörflichem Charakter',
    housing: 'viele Eigenheime mit großen Gärten auf locker bebauten Grundstücken, dazu alte Bauernhöfe und moderne Neubauten',
    districts: ['Gennebreck', 'Haßlinghausen', 'Niedersprockhövel'],
    tradeNote: 'Große Gärten, Bäume und Hanglagen: Bei Außenanlagen und Dacharbeiten spielen Wetter- und Bodenverhältnisse hier eine größere Rolle als in der Ebene.',
    surroundings: 'über dem Ruhrtal zwischen Hattingen, Witten und Wuppertal',
  },
  'unna': {
    name: 'Unna',
    character: 'Kreisstadt an der Hellweg-Börde, historischer Kern mit moderner Peripherie',
    housing: 'Fachwerk und Altbau in der Innenstadt, Zechensiedlungen der Zeche Königsborn, große Eigenheim- und Reihenhausgebiete der 1960er- bis 1980er-Jahre',
    districts: ['Innenstadt', 'Königsborn', 'Massen', 'Uelzen'],
    tradeNote: 'Massen und Königsborn haben ganze Straßenzüge gleichartiger Siedlungshäuser — wer hier ein Haus saniert, profitiert von Erfahrung mit genau dieser Bauart.',
    surroundings: 'Kreuzung von A1 und A44, zwischen Dortmund, Kamen und Werl',
  },
  'wetter-ruhr': {
    name: 'Wetter (Ruhr)',
    character: 'kleinstädtisch-ruhig an der Ruhr, mit Fachwerk in Alt-Wetter und grünem Ardey-Rücken',
    housing: 'Fachwerk in Alt-Wetter und Wengern, viele Hanglagen mit älteren Häusern, solide Eigenheime oberhalb des Ruhrtals',
    districts: ['Alt-Wetter', 'Wengern', 'Grundschöttel'],
    tradeNote: 'Hanglagen über der Ruhr: Entwässerung, Böschungssicherung und Zufahrten sind hier Standardthemen, die manche unterschätzen — wir nicht.',
    surroundings: 'im Ennepe-Ruhr-Kreis zwischen Witten, Hagen und Herdecke',
  },
  'witten': {
    name: 'Witten',
    character: 'Ruhrstadt mit Identität: von der Gründerzeit-Innenstadt bis zu Herbedes Villen',
    housing: 'Gründerzeit in der Innenstadt, Zechensiedlungen am Muttental (mit dem Bergbau-Museum Nachtigall!), Doppelhaushälften und Villen in Herbede und Bommern',
    districts: ['Innenstadt', 'Herbede', 'Bommern', 'Heven'],
    tradeNote: 'Witten vereint fast alles: Altbau, Siedlung, Villen, Hanglagen am Ardey. Dazu wissen wir um die typischen Bauschäden der Bergbaufolgelandschaft im Muttental.',
    surroundings: 'an der Ruhr zwischen Bochum, Hattingen und Wetter, an der A43 und A44',
  },
};

module.exports = CITY_FACTS;
